//! Reproducible benchmark for:
//! SSD -> host memory -> V80 HPU TFHE computation -> host memory -> optional SSD writeback.

use clap::{Parser, ValueEnum};
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};
use std::fs::{self, File};
use std::io::Write;
use std::panic;
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::time::{Instant, SystemTime, UNIX_EPOCH};
use tfhe::integer::hpu::ciphertext::HpuRadixCiphertext;
use tfhe::integer::{ClientKey, CompressedServerKey, RadixCiphertext};
use tfhe::shortint::parameters::KeySwitch32PBSParameters;
use tfhe_hpu_backend::prelude::*;

const INPUT_MAGIC: &[u8; 8] = b"HPUPIP1\0";
const CIPHERTEXT_MAGIC: &[u8; 8] = b"HPUCTX1\0";
const OUTPUT_MAGIC: &[u8; 8] = b"HPUOUT1\0";
const RESULT_CIPHERTEXT_MAGIC: &[u8; 8] = b"HPUCTR1\0";
const FORMAT_VERSION: u32 = 1;

#[derive(Clone, Copy, Debug, Serialize, ValueEnum)]
#[serde(rename_all = "kebab-case")]
enum Operation {
    Add,
    Sub,
    Mul,
}

impl Operation {
    fn as_str(self) -> &'static str {
        match self {
            Self::Add => "add",
            Self::Sub => "sub",
            Self::Mul => "mul",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, ValueEnum)]
#[serde(rename_all = "kebab-case")]
enum OperandMode {
    /// lhs and rhs are encrypted, then the HPU executes ct op ct.
    EncryptedEncrypted,
    /// lhs is encrypted, rhs stays clear, then the HPU executes ct op scalar.
    EncryptedClear,
}

impl OperandMode {
    fn as_str(self) -> &'static str {
        match self {
            Self::EncryptedEncrypted => "encrypted-encrypted",
            Self::EncryptedClear => "encrypted-clear",
        }
    }
}

#[derive(Clone, Copy, Debug, Serialize, ValueEnum)]
#[serde(rename_all = "kebab-case")]
enum OutputFormat {
    Binary,
    Text,
}

#[derive(Parser, Debug, Clone, Serialize)]
#[command(long_about = "Benchmark SSD -> host -> V80 HPU TFHE -> host -> optional SSD writeback.")]
struct Args {
    /// HPU TOML top-level configuration file.
    #[arg(
        long,
        default_value = "${HPU_BACKEND_DIR}/config_store/${HPU_CONFIG}/hpu_config.toml"
    )]
    config: ShellString,

    /// Disable the V80 backend fresh-reload fallback. If the current hardware cannot be reused,
    /// the benchmark exits with a blocker report instead of unloading drivers or rescanning PCIe.
    #[arg(long)]
    no_reload: bool,

    /// Legacy cleartext input path. Use --plaintext-input/--ciphertext-input plus key files for
    /// the recommended generated-dataset workflow.
    #[arg(long)]
    input: Option<PathBuf>,

    /// Visible decimal cleartext file with one "lhs rhs" pair per line. Used as correctness
    /// reference and as scalar source for encrypted-clear mode.
    #[arg(long)]
    plaintext_input: Option<PathBuf>,

    /// Serialized CPU RadixCiphertext input file generated by hpu_pipeline_dataset.
    #[arg(long)]
    ciphertext_input: Option<PathBuf>,

    /// Client key file generated alongside --ciphertext-input.
    #[arg(long)]
    client_key: Option<PathBuf>,

    /// Compressed server key file generated alongside --ciphertext-input.
    #[arg(long)]
    server_key: Option<PathBuf>,

    /// Optional output path. If omitted, SSD writeback is skipped.
    #[arg(long)]
    output: Option<PathBuf>,

    /// Optional serialized CPU RadixCiphertext result output. This writes encrypted HPU results
    /// after HPU-to-host transfer.
    #[arg(long)]
    ciphertext_output: Option<PathBuf>,

    /// Number of binary operations/records to benchmark.
    #[arg(long, default_value_t = 1024)]
    dataset_size: usize,

    /// Logical fixed-width binary plaintext payload size in bytes. When set, this overrides
    /// --dataset-size for record-count calculation.
    #[arg(long)]
    plaintext_bytes: Option<usize>,

    /// Number of records processed before dropping HPU variables.
    #[arg(long, default_value_t = 64)]
    batch_size: usize,

    /// Measured steady-state repetitions.
    #[arg(long, default_value_t = 5)]
    repetitions: usize,

    /// Full pipeline warmup repetitions. Warmups are not written to raw results.
    #[arg(long, default_value_t = 1)]
    warmups: usize,

    /// Unsigned integer width. Must be supported by the loaded HPU firmware.
    #[arg(long, default_value_t = 64)]
    integer_width: usize,

    /// HPU operation to benchmark.
    #[arg(long, value_enum, default_value_t = Operation::Add)]
    operation: Operation,

    /// Operand form to benchmark.
    #[arg(long, value_enum, default_value_t = OperandMode::EncryptedEncrypted)]
    operand_mode: OperandMode,

    /// Constant rhs value. In encrypted-clear mode it is passed as a clear HPU scalar. In
    /// encrypted-encrypted mode it is encrypted on host and used as the rhs ciphertext.
    #[arg(long, value_parser = parse_cli_u128)]
    clear_scalar: Option<u128>,

    /// Deterministic input generator seed.
    #[arg(long, default_value_t = 0x5eed_u64)]
    seed: u64,

    /// Create or overwrite --input with deterministic cleartext pairs before measuring.
    #[arg(long)]
    generate_input: bool,

    /// Overwrite an existing input file when --generate-input is used.
    #[arg(long)]
    force: bool,

    /// Call fsync on output and result files.
    #[arg(long)]
    sync_write: bool,

    /// Output format for optional --output writeback.
    #[arg(long, value_enum, default_value_t = OutputFormat::Binary)]
    output_format: OutputFormat,

    /// Directory for raw CSV/JSON and summary JSON.
    #[arg(long, default_value = "target/hpu-pipeline-bench")]
    results_dir: PathBuf,

    /// Stable run id. Defaults to unix timestamp milliseconds.
    #[arg(long)]
    run_id: Option<String>,
}

#[derive(Clone, Copy, Debug)]
struct Record {
    lhs: u128,
    rhs: u128,
}

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "kebab-case")]
enum InputKind {
    PlaintextGeneratedOrRead,
    SerializedCiphertext,
}

impl InputKind {
    fn as_str(self) -> &'static str {
        match self {
            Self::PlaintextGeneratedOrRead => "plaintext-generated-or-read",
            Self::SerializedCiphertext => "serialized-ciphertext",
        }
    }
}

#[derive(Serialize, Deserialize)]
struct CiphertextPair {
    lhs: RadixCiphertext,
    rhs: RadixCiphertext,
}

struct CiphertextDataset {
    ciphertext_record_bytes: Vec<Vec<u8>>,
}

enum PreparedInput {
    Plaintext,
    Ciphertext {
        plaintext: Vec<Record>,
        client_key: ClientKey,
        server_key: CompressedServerKey,
    },
}

#[derive(Debug, Serialize)]
struct InitBreakdown {
    device_open_ns: u128,
    key_load_or_gen_ns: u128,
    hpu_init_ns: u128,
    total_ns: u128,
}

#[derive(Debug, Default, Clone, Serialize)]
struct StageBreakdown {
    ssd_read_ns: u128,
    host_preprocessing_ns: u128,
    host_to_hpu_transfer_ns: u128,
    hpu_compute_ns: u128,
    hpu_to_host_transfer_ns: u128,
    host_postprocessing_ns: u128,
    ssd_writeback_ns: u128,
    total_ns: u128,
}

#[derive(Debug, Serialize)]
struct RepetitionResult {
    run_id: String,
    repetition: usize,
    operation: Operation,
    operand_mode: OperandMode,
    integer_width: usize,
    dataset_size: usize,
    batch_size: usize,
    input_kind: InputKind,
    input_path: String,
    plaintext_path: Option<String>,
    ciphertext_path: Option<String>,
    output_path: Option<String>,
    ciphertext_output_path: Option<String>,
    input_bytes: u64,
    plaintext_bytes: u64,
    output_bytes: u64,
    ciphertext_output_bytes: u64,
    throughput_ops_per_s: f64,
    validation_passed: bool,
    first_mismatch: Option<String>,
    stages: StageBreakdown,
}

#[derive(Debug, Serialize)]
struct Summary {
    measured_repetitions: usize,
    mean_total_ns: u128,
    min_total_ns: u128,
    max_total_ns: u128,
    mean_throughput_ops_per_s: f64,
    mean_stages_ns: StageBreakdown,
}

#[derive(Debug, Serialize)]
struct Environment {
    os: String,
    arch: String,
    hpu_feature: bool,
    hpu_v80_feature: bool,
    hpu_xrt_feature: bool,
    executable: Option<String>,
}

#[derive(Debug, Serialize)]
struct RepoInspection {
    workspace: &'static str,
    hpu_backend: &'static str,
    hpu_mockup: &'static str,
    reused_paths: Vec<&'static str>,
    stage_limitations: Vec<&'static str>,
}

#[derive(Debug, Serialize)]
struct Report {
    schema_version: &'static str,
    generated_at_unix_ms: u128,
    run_id: String,
    args: Args,
    environment: Environment,
    repo_inspection: RepoInspection,
    stage_definitions: Vec<StageDefinition>,
    init: InitBreakdown,
    repetitions: Vec<RepetitionResult>,
    summary: Summary,
}

#[derive(Debug, Serialize)]
struct StageDefinition {
    name: &'static str,
    definition: &'static str,
}

#[derive(Debug, Serialize)]
struct BlockerReport {
    schema_version: &'static str,
    generated_at_unix_ms: u128,
    run_id: String,
    args: Args,
    environment: Environment,
    blocker: String,
    note: &'static str,
}

fn main() -> ExitCode {
    let args = Args::parse();
    let run_id = args.run_id.clone().unwrap_or_else(|| unix_ms().to_string());

    let run_result = panic::catch_unwind({
        let args = args.clone();
        let run_id = run_id.clone();
        move || run(args, run_id)
    });

    match run_result {
        Ok(Ok(())) => ExitCode::SUCCESS,
        Ok(Err(err)) => {
            eprintln!("benchmark blocked: {err}");
            let _ = write_blocker_report(&args, &run_id, err);
            ExitCode::from(1)
        }
        Err(payload) => {
            let err = panic_payload_to_string(payload);
            eprintln!("benchmark blocked by panic: {err}");
            let _ = write_blocker_report(&args, &run_id, err);
            ExitCode::from(2)
        }
    }
}

fn run(args: Args, run_id: String) -> Result<(), String> {
    validate_args(&args)?;
    fs::create_dir_all(&args.results_dir)
        .map_err(|err| format!("unable to create results dir {:?}: {err}", args.results_dir))?;

    let dataset_size = effective_dataset_size(&args)?;
    if args.generate_input {
        generate_input_dataset(&args, dataset_size)?;
    }
    let input_kind = input_kind(&args);
    ensure_inputs_exist(&args, input_kind)?;

    let init_start = Instant::now();

    let t = Instant::now();
    let hpu_device = open_hpu_device(&args);
    let device_open_ns = elapsed_ns(t);

    let message_width = hpu_device.params().pbs_params.message_width;
    if args.integer_width % message_width != 0 {
        return Err(format!(
            "--integer-width {} is not divisible by HPU message width {}",
            args.integer_width, message_width
        ));
    }
    if !hpu_device
        .config()
        .firmware
        .integer_w
        .contains(&args.integer_width)
    {
        return Err(format!(
            "--integer-width {} is not enabled in HPU firmware config {:?}",
            args.integer_width,
            hpu_device.config().firmware.integer_w
        ));
    }
    let num_blocks = args.integer_width / message_width;

    let t = Instant::now();
    let prepared_input = prepare_input(&args, input_kind, dataset_size)?;
    let (cks, sks_compressed) = match &prepared_input {
        PreparedInput::Plaintext => {
            let cks = ClientKey::new(KeySwitch32PBSParameters::from(hpu_device.params()));
            let sks_compressed = CompressedServerKey::new_radix_compressed_server_key(&cks);
            (cks, sks_compressed)
        }
        PreparedInput::Ciphertext {
            client_key,
            server_key,
            ..
        } => (client_key.clone(), server_key.clone()),
    };
    let key_load_or_gen_ns = elapsed_ns(t);

    let t = Instant::now();
    tfhe::integer::hpu::init_device(&hpu_device, sks_compressed.clone())
        .map_err(|err| format!("HPU init_device failed: {err:?}"))?;
    let hpu_init_ns = elapsed_ns(t);

    let init = InitBreakdown {
        device_open_ns,
        key_load_or_gen_ns,
        hpu_init_ns,
        total_ns: elapsed_ns(init_start),
    };

    for warmup in 0..args.warmups {
        let _ = run_pipeline_repetition(
            &args,
            &run_id,
            warmup,
            input_kind,
            &prepared_input,
            dataset_size,
            &hpu_device,
            &cks,
            num_blocks,
        )?;
        hpu_device.mem_sanitizer();
    }

    let mut repetitions = Vec::with_capacity(args.repetitions);
    for rep in 0..args.repetitions {
        let result = run_pipeline_repetition(
            &args,
            &run_id,
            rep,
            input_kind,
            &prepared_input,
            dataset_size,
            &hpu_device,
            &cks,
            num_blocks,
        )?;
        repetitions.push(result);
        hpu_device.mem_sanitizer();
    }

    let report = Report {
        schema_version: "hpu-pipeline-bench/v1",
        generated_at_unix_ms: unix_ms(),
        run_id: run_id.clone(),
        args: args.clone(),
        environment: environment(),
        repo_inspection: repo_inspection(),
        stage_definitions: stage_definitions(),
        init,
        summary: summarize(&repetitions),
        repetitions,
    };

    let json_path = args.results_dir.join(format!("{run_id}.json"));
    let csv_path = args.results_dir.join(format!("{run_id}.csv"));
    write_json(&json_path, &report, args.sync_write)?;
    write_csv(&csv_path, &report.repetitions, args.sync_write)?;

    print_summary(&report);
    println!("raw_json={}", json_path.display());
    println!("raw_csv={}", csv_path.display());
    Ok(())
}

fn open_hpu_device(args: &Args) -> HpuDevice {
    let config_path = args.config.expand();
    if !args.no_reload {
        return HpuDevice::from_config(&config_path);
    }

    let mut config = HpuConfig::from_toml(&config_path);
    if let FFIMode::V80 { force_reload, .. } = &mut config.fpga.ffi {
        *force_reload = Some(ShellString::new("never".to_string()));
    }
    HpuDevice::new(config)
}

fn run_pipeline_repetition(
    args: &Args,
    run_id: &str,
    repetition: usize,
    input_kind: InputKind,
    prepared_input: &PreparedInput,
    dataset_size: usize,
    hpu_device: &HpuDevice,
    cks: &ClientKey,
    num_blocks: usize,
) -> Result<RepetitionResult, String> {
    let total_start = Instant::now();
    let mask = width_mask(args.integer_width);

    let t = Instant::now();
    let input_path = active_input_path(args, input_kind);
    let input_bytes = fs::read(input_path)
        .map_err(|err| format!("unable to read input {input_path:?}: {err}"))?;
    let ssd_read_ns = elapsed_ns(t);
    let input_len = input_bytes.len() as u64;

    let mut stages = StageBreakdown {
        ssd_read_ns,
        ..StageBreakdown::default()
    };

    let t = Instant::now();
    let plaintext_records = match input_kind {
        InputKind::PlaintextGeneratedOrRead => {
            parse_records(&input_bytes, dataset_size, args.integer_width, mask)?
        }
        InputKind::SerializedCiphertext => match prepared_input {
            PreparedInput::Ciphertext { plaintext, .. } => plaintext.clone(),
            PreparedInput::Plaintext => {
                unreachable!("prepared plaintext used with ciphertext mode")
            }
        },
    };
    let ciphertext_dataset = match input_kind {
        InputKind::PlaintextGeneratedOrRead => None,
        InputKind::SerializedCiphertext => Some(parse_ciphertext_dataset(
            &input_bytes,
            dataset_size,
            args.integer_width,
        )?),
    };
    stages.host_preprocessing_ns += elapsed_ns(t);

    let mut output_values = Vec::with_capacity(plaintext_records.len());
    let mut ciphertext_output_values = args
        .ciphertext_output
        .as_ref()
        .map(|_| Vec::with_capacity(plaintext_records.len()));
    let mut first_mismatch = None;

    for (batch_index, batch) in plaintext_records.chunks(args.batch_size).enumerate() {
        let t = Instant::now();
        let (lhs_cpu, rhs_cpu) = match ciphertext_dataset.as_ref() {
            Some(dataset) => {
                let start = batch_index * args.batch_size;
                let stop = start + batch.len();
                let mut lhs = Vec::with_capacity(batch.len());
                let mut rhs = match args.operand_mode {
                    OperandMode::EncryptedEncrypted => Some(Vec::with_capacity(batch.len())),
                    OperandMode::EncryptedClear => None,
                };
                for record_bytes in &dataset.ciphertext_record_bytes[start..stop] {
                    let pair: CiphertextPair = bincode::deserialize(record_bytes)
                        .map_err(|err| format!("unable to deserialize ciphertext record: {err}"))?;
                    lhs.push(pair.lhs);
                    if let Some(rhs) = rhs.as_mut() {
                        let rhs_ct = match args.clear_scalar {
                            Some(clear_scalar) => {
                                cks.encrypt_radix(clear_scalar & mask, num_blocks)
                            }
                            None => pair.rhs,
                        };
                        rhs.push(rhs_ct);
                    }
                }
                (lhs, rhs)
            }
            None => {
                let lhs = batch
                    .iter()
                    .map(|record| cks.encrypt_radix(record.lhs & mask, num_blocks))
                    .collect::<Vec<RadixCiphertext>>();
                let rhs = match args.operand_mode {
                    OperandMode::EncryptedEncrypted => Some(
                        batch
                            .iter()
                            .map(|record| {
                                cks.encrypt_radix(clear_rhs(args, record, mask), num_blocks)
                            })
                            .collect::<Vec<RadixCiphertext>>(),
                    ),
                    OperandMode::EncryptedClear => None,
                };
                (lhs, rhs)
            }
        };
        stages.host_preprocessing_ns += elapsed_ns(t);

        let t = Instant::now();
        let lhs_hpu = lhs_cpu
            .iter()
            .map(|ct| HpuRadixCiphertext::from_radix_ciphertext(ct, hpu_device))
            .collect::<Vec<_>>();
        let rhs_hpu = rhs_cpu.as_ref().map(|rhs| {
            rhs.iter()
                .map(|ct| HpuRadixCiphertext::from_radix_ciphertext(ct, hpu_device))
                .collect::<Vec<_>>()
        });
        stages.host_to_hpu_transfer_ns += elapsed_ns(t);

        let t = Instant::now();
        let mut hpu_results = Vec::with_capacity(batch.len());
        match (&args.operand_mode, rhs_hpu.as_ref()) {
            (OperandMode::EncryptedEncrypted, Some(rhs_hpu)) => {
                for (lhs, rhs) in lhs_hpu.iter().zip(rhs_hpu.iter()) {
                    hpu_results.push(exec_ct_ct(args.operation, lhs, rhs));
                }
            }
            (OperandMode::EncryptedClear, None) => {
                for (lhs, record) in lhs_hpu.iter().zip(batch.iter()) {
                    hpu_results.push(exec_ct_clear(
                        args.operation,
                        lhs,
                        clear_rhs(args, record, mask),
                    ));
                }
            }
            _ => unreachable!("operand mode and rhs HPU storage mismatch"),
        }
        for result in &hpu_results {
            result.wait();
        }
        stages.hpu_compute_ns += elapsed_ns(t);

        let t = Instant::now();
        let cpu_results = hpu_results
            .iter()
            .map(HpuRadixCiphertext::to_radix_ciphertext)
            .collect::<Vec<_>>();
        stages.hpu_to_host_transfer_ns += elapsed_ns(t);

        let t = Instant::now();
        for (offset, (record, ct)) in batch.iter().zip(cpu_results.iter()).enumerate() {
            let decrypted: u128 = cks.decrypt_radix(ct);
            let got = decrypted & mask;
            let rhs = rhs_for_reference(args, record, mask);
            let expected = reference(args.operation, record.lhs & mask, rhs, mask);
            if got != expected && first_mismatch.is_none() {
                first_mismatch = Some(format!(
                    "batch={batch_index},offset={offset},lhs=0x{:x},rhs=0x{:x},got=0x{:x},expected=0x{:x}",
                    record.lhs & mask,
                    rhs,
                    got,
                    expected
                ));
            }
            output_values.push(got);
        }
        stages.host_postprocessing_ns += elapsed_ns(t);

        if let Some(values) = ciphertext_output_values.as_mut() {
            values.extend(cpu_results);
        }
    }

    let mut output_bytes = 0;
    let mut ciphertext_output_bytes = 0;
    if args.output.is_some() || args.ciphertext_output.is_some() {
        let t = Instant::now();
        if let Some(output_path) = &args.output {
            output_bytes = write_output(output_path, &output_values, args)?;
        }
        if let (Some(ciphertext_output_path), Some(ciphertexts)) =
            (&args.ciphertext_output, ciphertext_output_values.as_ref())
        {
            ciphertext_output_bytes = write_ciphertext_output(
                ciphertext_output_path,
                ciphertexts,
                args.integer_width,
                args.sync_write,
            )?;
        }
        stages.ssd_writeback_ns += elapsed_ns(t);
    }

    stages.total_ns = elapsed_ns(total_start);
    let throughput_ops_per_s = if stages.total_ns == 0 {
        0.0
    } else {
        (plaintext_records.len() as f64) / (stages.total_ns as f64 / 1_000_000_000.0)
    };

    Ok(RepetitionResult {
        run_id: run_id.to_string(),
        repetition,
        operation: args.operation,
        operand_mode: args.operand_mode,
        integer_width: args.integer_width,
        dataset_size: plaintext_records.len(),
        batch_size: args.batch_size,
        input_kind,
        input_path: input_path.display().to_string(),
        plaintext_path: args
            .plaintext_input
            .as_ref()
            .map(|p| p.display().to_string()),
        ciphertext_path: args
            .ciphertext_input
            .as_ref()
            .map(|p| p.display().to_string()),
        output_path: args.output.as_ref().map(|p| p.display().to_string()),
        ciphertext_output_path: args
            .ciphertext_output
            .as_ref()
            .map(|p| p.display().to_string()),
        input_bytes: input_len,
        plaintext_bytes: plaintext_file_len(args).unwrap_or(0),
        output_bytes,
        ciphertext_output_bytes,
        throughput_ops_per_s,
        validation_passed: first_mismatch.is_none(),
        first_mismatch,
        stages,
    })
}

fn exec_ct_ct(
    operation: Operation,
    lhs: &HpuRadixCiphertext,
    rhs: &HpuRadixCiphertext,
) -> HpuRadixCiphertext {
    match operation {
        Operation::Add => lhs + rhs,
        Operation::Sub => lhs - rhs,
        Operation::Mul => lhs * rhs,
    }
}

fn exec_ct_clear(operation: Operation, lhs: &HpuRadixCiphertext, rhs: u128) -> HpuRadixCiphertext {
    match operation {
        Operation::Add => lhs + rhs,
        Operation::Sub => lhs - rhs,
        Operation::Mul => lhs * rhs,
    }
}

fn clear_rhs(args: &Args, record: &Record, mask: u128) -> u128 {
    args.clear_scalar.unwrap_or(record.rhs) & mask
}

fn rhs_for_reference(args: &Args, record: &Record, mask: u128) -> u128 {
    if let Some(clear_scalar) = args.clear_scalar {
        return clear_scalar & mask;
    }
    match args.operand_mode {
        OperandMode::EncryptedEncrypted => record.rhs & mask,
        OperandMode::EncryptedClear => clear_rhs(args, record, mask),
    }
}

fn reference(operation: Operation, lhs: u128, rhs: u128, mask: u128) -> u128 {
    match operation {
        Operation::Add => lhs.wrapping_add(rhs) & mask,
        Operation::Sub => lhs.wrapping_sub(rhs) & mask,
        Operation::Mul => lhs.wrapping_mul(rhs) & mask,
    }
}

fn validate_args(args: &Args) -> Result<(), String> {
    if args.dataset_size == 0 {
        return Err("--dataset-size must be greater than 0".to_string());
    }
    if args.batch_size == 0 {
        return Err("--batch-size must be greater than 0".to_string());
    }
    if args.repetitions == 0 {
        return Err("--repetitions must be greater than 0".to_string());
    }
    if args.integer_width == 0 || args.integer_width > 128 {
        return Err("--integer-width must be in 1..=128".to_string());
    }
    if matches!(args.plaintext_bytes, Some(0)) {
        return Err("--plaintext-bytes must be greater than 0".to_string());
    }
    let _ = effective_dataset_size(args)?;
    if args.ciphertext_input.is_some() {
        if args.generate_input {
            return Err(
                "--generate-input only applies to legacy --input mode; use hpu_pipeline_dataset for --ciphertext-input"
                    .to_string(),
            );
        }
        if args.plaintext_input.is_none() {
            return Err("--plaintext-input is required with --ciphertext-input".to_string());
        }
        if args.client_key.is_none() {
            return Err("--client-key is required with --ciphertext-input".to_string());
        }
        if args.server_key.is_none() {
            return Err("--server-key is required with --ciphertext-input".to_string());
        }
    } else if args.input.is_none() {
        return Err("--input is required unless --ciphertext-input is used".to_string());
    }
    Ok(())
}

fn effective_dataset_size(args: &Args) -> Result<usize, String> {
    if let Some(plaintext_bytes) = args.plaintext_bytes {
        let operand_bytes = args.integer_width.div_ceil(8);
        let record_bytes = operand_bytes * 2;
        if plaintext_bytes % record_bytes != 0 {
            return Err(format!(
                "--plaintext-bytes {plaintext_bytes} is not divisible by one lhs/rhs record ({record_bytes} bytes for {}-bit integers)",
                args.integer_width
            ));
        }
        let records = plaintext_bytes / record_bytes;
        if records == 0 {
            return Err(format!(
                "--plaintext-bytes {plaintext_bytes} is too small for one lhs/rhs record ({record_bytes} bytes)"
            ));
        }
        Ok(records)
    } else {
        Ok(args.dataset_size)
    }
}

fn input_kind(args: &Args) -> InputKind {
    if args.ciphertext_input.is_some() {
        InputKind::SerializedCiphertext
    } else {
        InputKind::PlaintextGeneratedOrRead
    }
}

fn ensure_inputs_exist(args: &Args, input_kind: InputKind) -> Result<(), String> {
    match input_kind {
        InputKind::PlaintextGeneratedOrRead => {
            let input = args.input.as_ref().expect("validated legacy input path");
            ensure_file_exists("--input", input)
        }
        InputKind::SerializedCiphertext => {
            ensure_file_exists(
                "--plaintext-input",
                args.plaintext_input
                    .as_ref()
                    .expect("validated plaintext input path"),
            )?;
            ensure_file_exists(
                "--ciphertext-input",
                args.ciphertext_input
                    .as_ref()
                    .expect("validated ciphertext input path"),
            )?;
            ensure_file_exists(
                "--client-key",
                args.client_key.as_ref().expect("validated client key path"),
            )?;
            ensure_file_exists(
                "--server-key",
                args.server_key.as_ref().expect("validated server key path"),
            )
        }
    }
}

fn ensure_file_exists(label: &str, path: &Path) -> Result<(), String> {
    if path.is_file() {
        Ok(())
    } else {
        Err(format!("{label} {path:?} does not exist or is not a file"))
    }
}

fn active_input_path(args: &Args, input_kind: InputKind) -> &Path {
    match input_kind {
        InputKind::PlaintextGeneratedOrRead => args
            .input
            .as_ref()
            .expect("validated legacy input path")
            .as_path(),
        InputKind::SerializedCiphertext => args
            .ciphertext_input
            .as_ref()
            .expect("validated ciphertext input path")
            .as_path(),
    }
}

fn plaintext_file_len(args: &Args) -> Option<u64> {
    let path = args.plaintext_input.as_ref().or(args.input.as_ref())?;
    fs::metadata(path).ok().map(|metadata| metadata.len())
}

fn prepare_input(
    args: &Args,
    input_kind: InputKind,
    dataset_size: usize,
) -> Result<PreparedInput, String> {
    match input_kind {
        InputKind::PlaintextGeneratedOrRead => Ok(PreparedInput::Plaintext),
        InputKind::SerializedCiphertext => {
            let plaintext_path = args
                .plaintext_input
                .as_ref()
                .expect("validated plaintext input path");
            let bytes = fs::read(plaintext_path).map_err(|err| {
                format!("unable to read plaintext input {plaintext_path:?}: {err}")
            })?;
            let plaintext =
                parse_text_records(&bytes, dataset_size, width_mask(args.integer_width))?;
            let client_key = read_bincode_file(
                args.client_key.as_ref().expect("validated client key path"),
                "client key",
            )?;
            let server_key = read_bincode_file(
                args.server_key.as_ref().expect("validated server key path"),
                "compressed server key",
            )?;
            Ok(PreparedInput::Ciphertext {
                plaintext,
                client_key,
                server_key,
            })
        }
    }
}

fn read_bincode_file<T: DeserializeOwned>(path: &Path, label: &str) -> Result<T, String> {
    let bytes = fs::read(path).map_err(|err| format!("unable to read {label} {path:?}: {err}"))?;
    bincode::deserialize(&bytes)
        .map_err(|err| format!("unable to deserialize {label} {path:?}: {err}"))
}

fn width_mask(width: usize) -> u128 {
    if width == 128 {
        u128::MAX
    } else {
        (1_u128 << width) - 1
    }
}

fn parse_records(
    bytes: &[u8],
    requested: usize,
    integer_width: usize,
    mask: u128,
) -> Result<Vec<Record>, String> {
    if bytes.starts_with(INPUT_MAGIC) {
        parse_binary_records(bytes, requested, integer_width, mask)
    } else {
        parse_text_records(bytes, requested, mask)
    }
}

fn parse_binary_records(
    bytes: &[u8],
    requested: usize,
    integer_width: usize,
    mask: u128,
) -> Result<Vec<Record>, String> {
    let header_len = 8 + 4 + 4 + 8 + 16;
    if bytes.len() < header_len {
        return Err("binary input is shorter than the HPU pipeline header".to_string());
    }
    let version = u32::from_le_bytes(bytes[8..12].try_into().unwrap());
    if version != FORMAT_VERSION {
        return Err(format!(
            "unsupported input format version {version}; expected {FORMAT_VERSION}"
        ));
    }
    let file_width = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
    if file_width != integer_width {
        return Err(format!(
            "input integer width {file_width} does not match --integer-width {integer_width}"
        ));
    }
    let count = u64::from_le_bytes(bytes[16..24].try_into().unwrap()) as usize;
    if count < requested {
        return Err(format!(
            "input contains {count} records but --dataset-size requested {requested}"
        ));
    }
    let record_bytes = &bytes[header_len..];
    if record_bytes.len() < count * 32 {
        return Err("binary input payload is truncated".to_string());
    }
    let mut records = Vec::with_capacity(requested);
    for i in 0..requested {
        let base = i * 32;
        let lhs = u128::from_le_bytes(record_bytes[base..base + 16].try_into().unwrap()) & mask;
        let rhs =
            u128::from_le_bytes(record_bytes[base + 16..base + 32].try_into().unwrap()) & mask;
        records.push(Record { lhs, rhs });
    }
    Ok(records)
}

fn parse_text_records(bytes: &[u8], requested: usize, mask: u128) -> Result<Vec<Record>, String> {
    let text = std::str::from_utf8(bytes)
        .map_err(|err| format!("input is neither HPU binary dataset nor UTF-8 text: {err}"))?;
    let mut values = Vec::new();
    for token in text.split_whitespace() {
        values.push(parse_u128_token(token)? & mask);
    }
    if values.len() < requested * 2 {
        return Err(format!(
            "text input has {} numeric tokens but {} are required for {} records",
            values.len(),
            requested * 2,
            requested
        ));
    }
    let mut records = Vec::with_capacity(requested);
    for pair in values.chunks_exact(2).take(requested) {
        records.push(Record {
            lhs: pair[0],
            rhs: pair[1],
        });
    }
    Ok(records)
}

fn parse_ciphertext_dataset(
    bytes: &[u8],
    requested: usize,
    integer_width: usize,
) -> Result<CiphertextDataset, String> {
    let header_len = 8 + 4 + 4 + 8 + 16;
    if bytes.len() < header_len {
        return Err("ciphertext input is shorter than the HPU ciphertext header".to_string());
    }
    if &bytes[0..8] != CIPHERTEXT_MAGIC {
        return Err("ciphertext input does not start with HPUCTX1 magic".to_string());
    }
    let version = u32::from_le_bytes(bytes[8..12].try_into().unwrap());
    if version != FORMAT_VERSION {
        return Err(format!(
            "unsupported ciphertext format version {version}; expected {FORMAT_VERSION}"
        ));
    }
    let file_width = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
    if file_width != integer_width {
        return Err(format!(
            "ciphertext integer width {file_width} does not match --integer-width {integer_width}"
        ));
    }
    let count = u64::from_le_bytes(bytes[16..24].try_into().unwrap()) as usize;
    if count < requested {
        return Err(format!(
            "ciphertext input contains {count} records but --dataset-size requested {requested}"
        ));
    }

    let mut offset = header_len;
    let mut ciphertext_record_bytes = Vec::with_capacity(requested);
    for index in 0..requested {
        if offset + 8 > bytes.len() {
            return Err(format!(
                "ciphertext input is truncated before record {index} length"
            ));
        }
        let len = u64::from_le_bytes(bytes[offset..offset + 8].try_into().unwrap()) as usize;
        offset += 8;
        if offset + len > bytes.len() {
            return Err(format!(
                "ciphertext input is truncated in record {index}: need {len} bytes"
            ));
        }
        ciphertext_record_bytes.push(bytes[offset..offset + len].to_vec());
        offset += len;
    }

    Ok(CiphertextDataset {
        ciphertext_record_bytes,
    })
}

fn parse_u128_token(token: &str) -> Result<u128, String> {
    if let Some(hex) = token
        .strip_prefix("0x")
        .or_else(|| token.strip_prefix("0X"))
    {
        u128::from_str_radix(hex, 16).map_err(|err| format!("invalid hex token {token:?}: {err}"))
    } else {
        token
            .parse::<u128>()
            .map_err(|err| format!("invalid decimal token {token:?}: {err}"))
    }
}

fn parse_cli_u128(token: &str) -> Result<u128, String> {
    parse_u128_token(token)
}

fn generate_input_dataset(args: &Args, dataset_size: usize) -> Result<(), String> {
    let input = args
        .input
        .as_ref()
        .ok_or_else(|| "--input is required with --generate-input".to_string())?;
    if input.exists() && !args.force {
        return Err(format!(
            "input {input:?} already exists; pass --force to overwrite it"
        ));
    }
    if let Some(parent) = input.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("unable to create input parent {parent:?}: {err}"))?;
    }
    let mask = width_mask(args.integer_width);
    let mut rng = StdRng::seed_from_u64(args.seed);
    let mut bytes = Vec::with_capacity(8 + 4 + 4 + 8 + 16 + dataset_size * 32);
    bytes.extend_from_slice(INPUT_MAGIC);
    bytes.extend_from_slice(&FORMAT_VERSION.to_le_bytes());
    bytes.extend_from_slice(&(args.integer_width as u32).to_le_bytes());
    bytes.extend_from_slice(&(dataset_size as u64).to_le_bytes());
    bytes.extend_from_slice(&(args.seed as u128).to_le_bytes());
    for _ in 0..dataset_size {
        let lhs = random_u128(&mut rng) & mask;
        let rhs = random_u128(&mut rng) & mask;
        bytes.extend_from_slice(&lhs.to_le_bytes());
        bytes.extend_from_slice(&rhs.to_le_bytes());
    }
    write_all(input, &bytes, args.sync_write)
}

fn random_u128(rng: &mut StdRng) -> u128 {
    ((rng.gen::<u64>() as u128) << 64) | (rng.gen::<u64>() as u128)
}

fn write_output(path: &Path, values: &[u128], args: &Args) -> Result<u64, String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("unable to create output parent {parent:?}: {err}"))?;
    }
    let bytes = match args.output_format {
        OutputFormat::Binary => {
            let mut bytes = Vec::with_capacity(8 + 4 + 4 + 8 + values.len() * 16);
            bytes.extend_from_slice(OUTPUT_MAGIC);
            bytes.extend_from_slice(&FORMAT_VERSION.to_le_bytes());
            bytes.extend_from_slice(&(args.integer_width as u32).to_le_bytes());
            bytes.extend_from_slice(&(values.len() as u64).to_le_bytes());
            for value in values {
                bytes.extend_from_slice(&value.to_le_bytes());
            }
            bytes
        }
        OutputFormat::Text => {
            let mut text = String::new();
            for value in values {
                use std::fmt::Write as _;
                writeln!(&mut text, "{value}").unwrap();
            }
            text.into_bytes()
        }
    };
    let len = bytes.len() as u64;
    write_all(path, &bytes, args.sync_write)?;
    Ok(len)
}

fn write_ciphertext_output(
    path: &Path,
    values: &[RadixCiphertext],
    integer_width: usize,
    sync: bool,
) -> Result<u64, String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| {
            format!("unable to create ciphertext output parent {parent:?}: {err}")
        })?;
    }
    let mut bytes = Vec::new();
    bytes.extend_from_slice(RESULT_CIPHERTEXT_MAGIC);
    bytes.extend_from_slice(&FORMAT_VERSION.to_le_bytes());
    bytes.extend_from_slice(&(integer_width as u32).to_le_bytes());
    bytes.extend_from_slice(&(values.len() as u64).to_le_bytes());
    bytes.extend_from_slice(&0_u128.to_le_bytes());
    for value in values {
        let record = bincode::serialize(value)
            .map_err(|err| format!("unable to serialize ciphertext output record: {err}"))?;
        bytes.extend_from_slice(&(record.len() as u64).to_le_bytes());
        bytes.extend_from_slice(&record);
    }
    let len = bytes.len() as u64;
    write_all(path, &bytes, sync)?;
    Ok(len)
}

fn write_all(path: &Path, bytes: &[u8], sync: bool) -> Result<(), String> {
    let mut file = File::create(path).map_err(|err| format!("unable to create {path:?}: {err}"))?;
    file.write_all(bytes)
        .map_err(|err| format!("unable to write {path:?}: {err}"))?;
    if sync {
        file.sync_all()
            .map_err(|err| format!("unable to fsync {path:?}: {err}"))?;
    }
    Ok(())
}

fn write_json<T: Serialize>(path: &Path, value: &T, sync: bool) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("unable to create json parent {parent:?}: {err}"))?;
    }
    let bytes = serde_json::to_vec_pretty(value)
        .map_err(|err| format!("unable to encode json {path:?}: {err}"))?;
    write_all(path, &bytes, sync)
}

fn write_csv(path: &Path, repetitions: &[RepetitionResult], sync: bool) -> Result<(), String> {
    let mut csv = String::new();
    csv.push_str("run_id,repetition,operation,operand_mode,integer_width,dataset_size,batch_size,input_kind,input_path,plaintext_path,ciphertext_path,output_path,ciphertext_output_path,input_bytes,plaintext_bytes,output_bytes,ciphertext_output_bytes,throughput_ops_per_s,validation_passed,first_mismatch,ssd_read_ns,host_preprocessing_ns,host_to_hpu_transfer_ns,hpu_compute_ns,hpu_to_host_transfer_ns,host_postprocessing_ns,ssd_writeback_ns,total_ns\n");
    for r in repetitions {
        use std::fmt::Write as _;
        writeln!(
            &mut csv,
            "{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{:.6},{},{},{},{},{},{},{},{},{},{}",
            csv_escape(&r.run_id),
            r.repetition,
            r.operation.as_str(),
            r.operand_mode.as_str(),
            r.integer_width,
            r.dataset_size,
            r.batch_size,
            r.input_kind.as_str(),
            csv_escape(&r.input_path),
            csv_escape(r.plaintext_path.as_deref().unwrap_or("")),
            csv_escape(r.ciphertext_path.as_deref().unwrap_or("")),
            csv_escape(r.output_path.as_deref().unwrap_or("")),
            csv_escape(r.ciphertext_output_path.as_deref().unwrap_or("")),
            r.input_bytes,
            r.plaintext_bytes,
            r.output_bytes,
            r.ciphertext_output_bytes,
            r.throughput_ops_per_s,
            r.validation_passed,
            csv_escape(r.first_mismatch.as_deref().unwrap_or("")),
            r.stages.ssd_read_ns,
            r.stages.host_preprocessing_ns,
            r.stages.host_to_hpu_transfer_ns,
            r.stages.hpu_compute_ns,
            r.stages.hpu_to_host_transfer_ns,
            r.stages.host_postprocessing_ns,
            r.stages.ssd_writeback_ns,
            r.stages.total_ns,
        )
        .unwrap();
    }
    write_all(path, csv.as_bytes(), sync)
}

fn csv_escape(value: &str) -> String {
    if value.contains([',', '"', '\n', '\r']) {
        format!("\"{}\"", value.replace('"', "\"\""))
    } else {
        value.to_string()
    }
}

fn write_blocker_report(args: &Args, run_id: &str, blocker: String) -> Result<(), String> {
    fs::create_dir_all(&args.results_dir)
        .map_err(|err| format!("unable to create blocker results dir: {err}"))?;
    let report = BlockerReport {
        schema_version: "hpu-pipeline-bench/blocker-v1",
        generated_at_unix_ms: unix_ms(),
        run_id: run_id.to_string(),
        args: args.clone(),
        environment: environment(),
        blocker,
        note: "No benchmark measurements were fabricated. Fix the blocker and rerun.",
    };
    let path = args.results_dir.join(format!("{run_id}.blocker.json"));
    write_json(&path, &report, args.sync_write)
}

fn summarize(repetitions: &[RepetitionResult]) -> Summary {
    if repetitions.is_empty() {
        return Summary {
            measured_repetitions: 0,
            mean_total_ns: 0,
            min_total_ns: 0,
            max_total_ns: 0,
            mean_throughput_ops_per_s: 0.0,
            mean_stages_ns: StageBreakdown::default(),
        };
    }

    let mut mean = StageBreakdown::default();
    let mut min_total = u128::MAX;
    let mut max_total = 0;
    let mut throughput = 0.0;
    for rep in repetitions {
        let s = &rep.stages;
        mean.ssd_read_ns += s.ssd_read_ns;
        mean.host_preprocessing_ns += s.host_preprocessing_ns;
        mean.host_to_hpu_transfer_ns += s.host_to_hpu_transfer_ns;
        mean.hpu_compute_ns += s.hpu_compute_ns;
        mean.hpu_to_host_transfer_ns += s.hpu_to_host_transfer_ns;
        mean.host_postprocessing_ns += s.host_postprocessing_ns;
        mean.ssd_writeback_ns += s.ssd_writeback_ns;
        mean.total_ns += s.total_ns;
        min_total = min_total.min(s.total_ns);
        max_total = max_total.max(s.total_ns);
        throughput += rep.throughput_ops_per_s;
    }
    let n = repetitions.len() as u128;
    mean.ssd_read_ns /= n;
    mean.host_preprocessing_ns /= n;
    mean.host_to_hpu_transfer_ns /= n;
    mean.hpu_compute_ns /= n;
    mean.hpu_to_host_transfer_ns /= n;
    mean.host_postprocessing_ns /= n;
    mean.ssd_writeback_ns /= n;
    mean.total_ns /= n;

    Summary {
        measured_repetitions: repetitions.len(),
        mean_total_ns: mean.total_ns,
        min_total_ns: min_total,
        max_total_ns: max_total,
        mean_throughput_ops_per_s: throughput / repetitions.len() as f64,
        mean_stages_ns: mean,
    }
}

fn print_summary(report: &Report) {
    println!("HPU pipeline benchmark summary");
    println!("run_id={}", report.run_id);
    println!("init_total_ms={:.3}", ns_to_ms(report.init.total_ns));
    println!(
        "steady_mean_total_ms={:.3}",
        ns_to_ms(report.summary.mean_total_ns)
    );
    println!(
        "steady_mean_throughput_ops_s={:.3}",
        report.summary.mean_throughput_ops_per_s
    );
    println!(
        "validation={}",
        if report.repetitions.iter().all(|r| r.validation_passed) {
            "passed"
        } else {
            "failed"
        }
    );
}

fn stage_definitions() -> Vec<StageDefinition> {
    vec![
        StageDefinition {
            name: "ssd_read",
            definition: "fs::read(input) only; OS page cache state is controlled externally.",
        },
        StageDefinition {
            name: "host_preprocessing",
            definition: "input parse, clear reference preparation, CPU-side radix encryption in plaintext mode, and CPU radix ciphertext deserialization in ciphertext mode.",
        },
        StageDefinition {
            name: "host_to_hpu_transfer",
            definition: "CPU radix ciphertext to HpuRadixCiphertext staging. On V80 this includes QDMA writes to board memory.",
        },
        StageDefinition {
            name: "hpu_compute",
            definition: "HPU IOp dispatch and wait for completion ack.",
        },
        StageDefinition {
            name: "hpu_to_host_transfer",
            definition: "HpuRadixCiphertext to CPU radix ciphertext readback. On V80 this includes QDMA C2H reads.",
        },
        StageDefinition {
            name: "host_postprocessing",
            definition: "decrypt, validate against cleartext reference, and prepare output buffer.",
        },
        StageDefinition {
            name: "ssd_writeback",
            definition: "optional decrypted output and encrypted ciphertext result file writes; fsync only when --sync-write is passed.",
        },
    ]
}

fn repo_inspection() -> RepoInspection {
    RepoInspection {
        workspace: "tfhe-rs/Cargo.toml",
        hpu_backend: "backends/tfhe-hpu-backend",
        hpu_mockup: "mockups/tfhe-hpu-mockup",
        reused_paths: vec![
            "tfhe/examples/hpu/bench.rs",
            "tfhe/examples/hpu/hlapi.rs",
            "tfhe/src/integer/hpu/ciphertext/mod.rs",
            "backends/tfhe-hpu-backend/src/interface/variable.rs",
            "backends/tfhe-hpu-backend/src/ffi/v80/qdma.rs",
        ],
        stage_limitations: vec![
            "V80 H2D is measured at HpuRadixCiphertext staging because V80 MemZone::write_bytes uses QDMA pwrite.",
            "HPU compute is measured from IOp dispatch through wait/ack; low-level RTL sub-stages are not exposed by the public API.",
            "Cold SSD cache requires external OS setup such as drop_caches; the harness does not require root and does not alter kernel caches.",
        ],
    }
}

fn environment() -> Environment {
    Environment {
        os: std::env::consts::OS.to_string(),
        arch: std::env::consts::ARCH.to_string(),
        hpu_feature: cfg!(feature = "hpu"),
        hpu_v80_feature: cfg!(feature = "hpu-v80"),
        hpu_xrt_feature: cfg!(feature = "hpu-xrt"),
        executable: std::env::current_exe()
            .ok()
            .map(|path| path.display().to_string()),
    }
}

fn elapsed_ns(start: Instant) -> u128 {
    start.elapsed().as_nanos()
}

fn ns_to_ms(ns: u128) -> f64 {
    ns as f64 / 1_000_000.0
}

fn unix_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

fn panic_payload_to_string(payload: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = payload.downcast_ref::<&str>() {
        (*s).to_string()
    } else if let Some(s) = payload.downcast_ref::<String>() {
        s.clone()
    } else {
        "non-string panic payload".to_string()
    }
}
