use clap::Parser;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use tfhe::core_crypto::prelude::LweCiphertextOwned;
use tfhe::shortint::ciphertext::{Degree, NoiseLevel};
use tfhe::shortint::client_key::atomic_pattern::KS32AtomicPatternClientKey;
use tfhe::shortint::client_key::GenericClientKey;
use tfhe::shortint::Ciphertext;

type KS32ClientKey = GenericClientKey<KS32AtomicPatternClientKey>;

#[derive(Parser, Debug, Clone)]
#[command(
    long_about = "Verify SUDA lwe_encrypt HLS u8-radix ciphertext words with the saved tfhe-rs KS32 ClientKey."
)]
struct Args {
    /// Serialized shortint KS32 ClientKey generated by hpu_export_lwe_encrypt_key.
    #[arg(long)]
    client_key: PathBuf,

    /// Binary ciphertext dump generated by the SUDA lwe_encrypt C simulation testbench.
    #[arg(long)]
    ciphertext_dump: PathBuf,
}

#[derive(Debug)]
struct U8RadixDump {
    mask_dimension: usize,
    inputs: Vec<u8>,
    radix_blocks_per_input: usize,
    message_width: usize,
    carry_width: usize,
    padding_bit_width: usize,
    delta_log2: usize,
    ciphertext_words: Vec<u64>,
}

fn main() -> ExitCode {
    let args = Args::parse();
    match run(&args) {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            eprintln!("verification failed: {err}");
            ExitCode::from(1)
        }
    }
}

fn run(args: &Args) -> Result<(), String> {
    let client_key_bytes = fs::read(&args.client_key)
        .map_err(|err| format!("unable to read {:?}: {err}", args.client_key))?;
    let client_key: KS32ClientKey = bincode::deserialize(&client_key_bytes)
        .map_err(|err| format!("unable to deserialize {:?}: {err}", args.client_key))?;
    let dump = read_u8_radix_dump(&args.ciphertext_dump)?;
    let params = client_key.parameters();

    let expected_mask_dimension = params.encryption_lwe_dimension().0;
    if dump.mask_dimension != expected_mask_dimension {
        return Err(format!(
            "mask dimension mismatch: dump={}, client_key={}",
            dump.mask_dimension, expected_mask_dimension
        ));
    }

    if dump.message_width != params.message_modulus().0.ilog2() as usize {
        return Err(format!(
            "message width mismatch: dump={}, client_key_message_modulus={}",
            dump.message_width,
            params.message_modulus().0
        ));
    }

    let expected_delta_log2 =
        u64::BITS as usize - dump.message_width - dump.carry_width - dump.padding_bit_width;
    if dump.delta_log2 != expected_delta_log2 {
        return Err(format!(
            "delta_log2 mismatch: dump={}, expected={}",
            dump.delta_log2, expected_delta_log2
        ));
    }

    let ciphertext_word_count = dump.mask_dimension + 1;
    let expected_ciphertexts = dump.inputs.len() * dump.radix_blocks_per_input;
    if dump.ciphertext_words.len() != expected_ciphertexts * ciphertext_word_count {
        return Err(format!(
            "ciphertext word count mismatch: dump={}, expected={}",
            dump.ciphertext_words.len(),
            expected_ciphertexts * ciphertext_word_count
        ));
    }

    for (input_index, &clear_u8) in dump.inputs.iter().enumerate() {
        let mut reconstructed = 0u8;

        for block_index in 0..dump.radix_blocks_per_input {
            let ciphertext_index = input_index * dump.radix_blocks_per_input + block_index;
            let start = ciphertext_index * ciphertext_word_count;
            let end = start + ciphertext_word_count;
            let lwe = LweCiphertextOwned::from_container(
                dump.ciphertext_words[start..end].to_vec(),
                params.ciphertext_modulus(),
            );
            let ct = Ciphertext::new(
                lwe,
                Degree::new(params.message_modulus().0 - 1),
                NoiseLevel::NOMINAL,
                params.message_modulus(),
                params.carry_modulus(),
                params.atomic_pattern(),
            );

            let decrypted = client_key.decrypt(&ct);
            let expected_block = u64::from(clear_u8 >> (block_index * dump.message_width))
                & ((1u64 << dump.message_width) - 1);
            if decrypted != expected_block {
                return Err(format!(
                    "decrypt mismatch at input={}, block={}: got={}, expected={}",
                    input_index, block_index, decrypted, expected_block
                ));
            }
            reconstructed |= (decrypted as u8) << (block_index * dump.message_width);
        }

        if reconstructed != clear_u8 {
            return Err(format!(
                "u8 reconstruct mismatch at input={}: got=0x{reconstructed:02x}, expected=0x{clear_u8:02x}",
                input_index
            ));
        }
    }

    println!("client_key_file={}", args.client_key.display());
    println!("ciphertext_dump={}", args.ciphertext_dump.display());
    println!("mask_dimension={}", dump.mask_dimension);
    println!("u8_inputs={}", dump.inputs.len());
    println!("radix_blocks={expected_ciphertexts}");
    println!("tfhe_client_key_decrypt_checked=yes");

    Ok(())
}

fn read_u8_radix_dump(path: &Path) -> Result<U8RadixDump, String> {
    let bytes = fs::read(path).map_err(|err| format!("unable to read {path:?}: {err}"))?;
    let mut cursor = 0usize;

    if bytes.len() < 8 || &bytes[..8] != b"LWEHLS01" {
        return Err(format!("{path:?} is not a LWEHLS01 dump"));
    }
    cursor += 8;

    let version = read_le64(&bytes, &mut cursor)?;
    if version != 1 {
        return Err(format!("unsupported dump version {version}"));
    }

    let mask_dimension = read_le64(&bytes, &mut cursor)? as usize;
    let input_count = read_le64(&bytes, &mut cursor)? as usize;
    let radix_blocks_per_input = read_le64(&bytes, &mut cursor)? as usize;
    let message_width = read_le64(&bytes, &mut cursor)? as usize;
    let carry_width = read_le64(&bytes, &mut cursor)? as usize;
    let padding_bit_width = read_le64(&bytes, &mut cursor)? as usize;
    let delta_log2 = read_le64(&bytes, &mut cursor)? as usize;
    let ciphertext_word_count = read_le64(&bytes, &mut cursor)? as usize;

    let mut inputs = Vec::with_capacity(input_count);
    for _ in 0..input_count {
        let input = read_le64(&bytes, &mut cursor)?;
        if input > u8::MAX as u64 {
            return Err(format!("u8 input value out of range: {input}"));
        }
        inputs.push(input as u8);
    }

    let mut ciphertext_words = Vec::with_capacity(ciphertext_word_count);
    for _ in 0..ciphertext_word_count {
        ciphertext_words.push(read_le64(&bytes, &mut cursor)?);
    }

    if cursor != bytes.len() {
        return Err(format!(
            "trailing bytes in {path:?}: consumed={}, total={}",
            cursor,
            bytes.len()
        ));
    }

    Ok(U8RadixDump {
        mask_dimension,
        inputs,
        radix_blocks_per_input,
        message_width,
        carry_width,
        padding_bit_width,
        delta_log2,
        ciphertext_words,
    })
}

fn read_le64(bytes: &[u8], cursor: &mut usize) -> Result<u64, String> {
    let end = *cursor + 8;
    let chunk = bytes
        .get(*cursor..end)
        .ok_or_else(|| "unexpected end of dump".to_string())?;
    let mut value = 0u64;
    for (idx, byte) in chunk.iter().enumerate() {
        value |= u64::from(*byte) << (idx * 8);
    }
    *cursor = end;
    Ok(value)
}
